[build]
builder = "RAILPACK"

[deploy]
startCommand = "npm run start" # Or your specific production start command
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
maxRestartCount = 10
