[build]
builder = "RAILPACK"

[deploy]
startCommand = "npm run start"   # This now works with the fix above
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
maxRestartCount = 10
